targets:
  $default:
    sources:
      - lib/**
      - .env
      - $packages$
    builders:
      json_serializable:
        options:
          field_rename: snake
        generate_for:
          - lib/data/**/*.dart
      retrofit_generator:
        generate_for:
          - lib/data/**/*.dart